### ISSUE TITLE
git-set-commit-status task fails when pipeline triggered from non-SCM trigger

### ISSUE THREAD

**Issue by nastacio** [open-toolchain/tekton-catalog#118]
Conditional branching of paths is hard to achieve in Tekton, so I propose that this task looks at the trigger of the pipeline and simply returns successfully if executed within the context of the pipeline being triggered by something like a timed or manual trigger.

**Comment by jauninb** [comment]
@nastacio can you be more specific on the use-case you are trying to achieve ?
This task is expecting to set a commit status on a given revision/commit id
The commit id can be given as a parameters using the `revision` param - see https://github.com/open-toolchain/tekton-catalog/blob/764b9733ff0837e85e91dec577c1e919b22a1a86/git/task-set-commit-status.yaml#L29

If your goal is to skip a given task invocation in your tekton pipeline according to the trigger, maybe condition can help or a refine of the tekton pipeline flow

**Comment by nastacio** [comment]
> @nastacio can you be more specific on the use-case you are trying to achieve ?
> This task is expecting to set a commit status on a given revision/commit id
> The commit id can be given as a parameters using the `revision` param - see
> 
> https://github.com/open-toolchain/tekton-catalog/blob/764b9733ff0837e85e91dec577c1e919b22a1a86/git/task-set-commit-status.yaml#L29
> 
> If your goal is to skip a given task invocation in your tekton pipeline according to the trigger, maybe condition can help or a refine of the tekton pipeline flow

More specific: if you put the current task in a pipeline, the task will fail when the pipeline is invoked with a manual trigger.
With this small modification, it does not.

I know every user can eventually bump into the problem and realize they can add a condition to avoid running the task, but the suggestion here would save people a lot of time without detracting from the purpose of the sample.

**Comment by ejodet** [comment]
PR https://github.com/open-toolchain/tekton-catalog/pull/119

**Comment by jauninb** [comment]
This task can be invoked from non SCM Git trigger pipeline if the commit is provided using git-clone task output for instance - in case of manual run
Preventing this in the task implementation is not appropriate
Closing this issue
