### ISSUE TITLE
[suggestion] Run tekton-lint on commits and PRs

### ISSUE THREAD

**Issue by docwhat** [open-toolchain/tekton-catalog#123]
May I suggestion running [`tekton-lint`](https://github.com/IBM/tekton-lint#readme) on every commit and PR?

If could also be used for branch protection.

You can use this to run it via docker:

```sh
# using docker
docker run \
    --rm \
    --tty \
    "--env=TERM=${TERM}" \
    "--volume=${PWD}:/src:ro" \
    "--workdir=/src" \
    node \
    npx tekton-lint --format=stylish "**/*.yaml"
```

or if you have node installed:

```sh
# using node 12+
npx tekton-lint --format=stylish "**/*.yaml"
```

I can submit a PR for a `script/lint` and/or for the CI system of your choice.

**Comment by jauninb** [comment]
That is a great idea. This is something that definitively needs to be considered

**Comment by docwhat** [comment]
I can create a PR for you for GitHub Actions if you'd like.

**Comment by jauninb** [comment]
As this tekton tasks catalog is hosting tekton tasks with affinity to CD-Tekton support (ie CD Tekton support awareness), it should be implemented using a CD Tekton pipeline - https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-tekton-pipelines

**Comment by jauninb** [comment]
This has been implemented and is using IBM Cloud CD Tekton Pipeline support to the CI Quality check tasks as described https://github.com/open-toolchain/tekton-catalog#criteria-for-code-submission
