### ISSUE TITLE
Allow set-status pending when already pending to be a no-op

### ISSUE THREAD

**Issue by celek** [open-toolchain/tekton-catalog#154]
Setting status to pending in gitlab when status is already pending causes a HTTP 400
Can we check the status if we are in gitlab AND we want to set to pending - and if already pending, then do not attempt to set the status ? 
@jauninb FYI

**Comment by darosale** [comment]
@jauninb Do you have any information on this? We had a period where we were not seeing this issue (Nov. 13-Jan.14) but now it has resurfaced.

**Comment by jauninb** [comment]
@darosale not that I am aware of. I will investigate

**Comment by jauninb** [comment]
https://github.ibm.com/org-ids/roadmap/issues/18123

**Comment by jauninb** [comment]
Closing in favor of the github.ibm.com issue
