### ISSUE TITLE
kubernetes-service: "ibmcloud ks cluster config" with "--export" parameter?

### ISSUE THREAD

**Issue by data-henrik** [open-toolchain/tekton-catalog#170]
the tasks defined under kubernetes-service use the command `ibmcloud ks cluster config` and a parameter `--export`. That parameter is not documented here: https://cloud.ibm.com/docs/containers?topic=containers-cli-plugin-kubernetes-service-cli#cs_cluster_config

When trying that command locally on version 1.x, that parameter causes an error. Is it still valid?

**Comment by ejodet** [comment]
@jauninb ^^

**Comment by data-henrik** [comment]
I checked that the images are based on the old 2.6 which supports the old ibmcloud ks version. So the question is when you will switch to the newer pipeline images?

**Comment by jauninb** [comment]
https://github.ibm.com/org-ids/roadmap/issues/16322
