### ISSUE TITLE
task-deploy-to-kubernetes fails due to not being authenticated to OpenShift cluster

### ISSUE THREAD

**Issue by gasgithub** [open-toolchain/tekton-catalog#188]
I followed the tutorial https://www.ibm.com/cloud/architecture/tutorials/develop-kubernetes-app-with-code-risk-analyzer, but pipeline fails on deploy-to-kubernetes and check-health steps due to not being authenticated to cluster, with the following messages:

```
Check ability to get a kubernetes deployment in test-proj using kubectl CLI
error: EOF
```
After I added some additional testing commands I noticed that user is not authenticated to cluster:
```
++ echo 'Check ability to create a kubernetes deployment in test-proj using kubectl CLI #### TESTING'
++ oc projects
Check ability to create a kubernetes deployment in test-proj using kubectl CLI #### TESTING
Error from server (Forbidden): namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope
```

I had to add scripts from commons repo to my app and change them to include the following code that authenticates to OCP, which I took from your other tutorial:
```
ibmcloud ks cluster config -c "${PIPELINE_KUBERNETES_CLUSTER_NAME}";
if which oc > /dev/null && ibmcloud ks cluster get -c "${PIPELINE_KUBERNETES_CLUSTER_NAME}" --json | jq -e '.type=="openshift"' > /dev/null; then oc login -u apikey -p "${PIPELINE_BLUEMIX_API_KEY}" ; fi;
```

So looks like task definition is missing proper authentication to cluster that it is deploying to....

**Comment by jauninb** [comment]
Fixed
